{
 "title": "Flask Web Application by Kienlt",
 "description": "Dashboard Author: Kienlt\npip install -U flask_prometheus_metrics\nhttps://github.com/pilosus/flask_prometheus_metrics/tree/master",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": {
     "query": "label_values(flask_exporter_info{service=\"flask\"},serviceName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{serviceName=\"$Service\"} / 1024 / 1024",
     "legendFormat": "$Service"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{serviceName=\"$Service\"} / 1024 / 1024",
     "legendFormat": "$Service"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{serviceName=\"$Service\"}[$__range]))",
     "legendFormat": "$Service"
    }
   ]
  },
  { "title": "Reponses Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rate success responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{status!~\"4..|5..\"}[$__range]))",
     "legendFormat": "Total success requests (Count)"
    },
    {
     "expr": "(sum(rate(flask_http_request_total{status!~\"4..|5..\"}[$__range])) \n/ \nsum(rate(flask_http_request_total[$__range]))) \n* 100",
     "legendFormat": "Percent success requests (%)"
    }
   ]
  },
  {
   "title": "Rate 4xx responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{status=~\"4..\"}[$__range]))",
     "legendFormat": "Total 4xx (Count)"
    },
    {
     "expr": "(sum(rate(flask_http_request_total{status=~\"4..\"}[$__range])) \n/ \nsum(rate(flask_http_request_total[$__range]))) \n* 100",
     "legendFormat": "Percent 4xx (%)"
    }
   ]
  },
  {
   "title": "Rate 5xx responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{status=~\"5..\"}[$__range]))",
     "legendFormat": "Total 5xx (Count)"
    },
    {
     "expr": "(sum(rate(flask_http_request_total{status=~\"5..\"}[$__range])) \n/ \nsum(rate(flask_http_request_total[$__range]))) \n* 100",
     "legendFormat": "Percent 5xx (%)"
    }
   ]
  }
 ]
}